# Generated by Django 5.1 on 2024-08-08 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="task_board",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="task_board.taskboard"),
            preserve_default=False,
        ),
    ]
