# Generated by Django 5.1 on 2024-08-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_board", "0002_remove_taskboard_icon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="taskboard",
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="DailyTaskStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("todo_count", models.PositiveIntegerField(default=0)),
                ("in_progress_count", models.PositiveIntegerField(default=0)),
                ("done_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "unique_together": {("date",)},
            },
        ),
    ]
