# Generated by Django 5.1 on 2024-08-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_board", "0002_task_task_board"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="postponed_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("TODO", "To Do"),
                    ("IN_PROGRESS", "In Progress"),
                    ("DONE", "Done"),
                    ("POSTPONED", "Postponed"),
                ],
                default="TODO",
                max_length=20,
            ),
        ),
    ]
