# Generated by Django 5.1 on 2024-08-08 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_board", "0003_task_postponed_to_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="task_board.taskboard", to_field="board_uuid"
            ),
        ),
    ]
