# Generated by Django 5.1 on 2024-11-06 18:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_board", "0004_dailytaskstats_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dailytaskstats",
            unique_together={("user", "date")},
        ),
    ]
