# Generated by Django 5.1 on 2024-08-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_board", "0005_taskboard_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="taskboard",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
