# Generated by Django 5.1 on 2024-08-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
